SET BatchPath="%~dp0PARTS"

CALL %BatchPath%\1_BUILD_CORE.bat
CALL %BatchPath%\2_PUBLISH_NEW_CORE_BUILD.bat
CALL %BatchPath%\3_DELETE_CORE_PACKAGES_FROM_CUSTOM_PROJECT.bat
CALL %BatchPath%\4_RESTORE_NUGET.bat
CALL %BatchPath%\5_BUILD_CUSTOM_PROJECT.bat


