version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile.webapi
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Custom.Gravitate.WebAPI/AppSettings.config:/inetpub/wwwroot/AppSettings.config:ro
      - ./Custom.Gravitate.WebAPI/Web.config:/inetpub/wwwroot/Web.config:ro
    networks:
      - gravitate-network

networks:
  gravitate-network:
    driver: bridge